<a href="https://colab.research.google.com/github/Prasanna1Mula/Incometax-code/blob/main/Data_Science_essentials_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# comments
#Hello people!!
X=3
X=X*3
print(X)


9


In [3]:
numOfLaptops = 3
ownerName= "Prasanna Mula"
print("number of laptops = ", numOfLaptops)
print("Owners Name = ", ownerName)

number of laptops =  3
Owners Name =  Prasanna Mula


In [4]:
#Airthmetic operations
a = 10
b= 4

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

14
6
40
2.5
2
10000


In [6]:
#Logical operators
a=5
b=8

print(a>3 and a<7)
print(a>6 or b<7)
print(not(a>3))


True
False
False


In [8]:
#User input
city = input("Where do you live?\n")
print("\n The city you live is : " + city)


Where do you live?
Visakhapatnam

 The city you live is : Visakhapatnam


**NumPy and Pandas**

In [12]:
 import numpy as np

 numbers = [1,2,3,4,5],["hello","learners"]
 numbers = np.array(numbers)
 print("Two dimensional Array : ", numbers)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
import numpy as np

eye_mat = np.eye(4)
print("One across diagonals: \n\n",eye_mat)

One across diagonals: 

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
import numpy as np

random_print = np.random.randint(0,100,10)
print("Random numbers from 0 to 100 printing 10:\n\n",random_print)



Random numbers from 0 to 100 printing 10:

 [43 40 41 44 45 36 64 25 49 28]


Printing last element in the array

In [14]:
names = np.array(["Anisha","Mihir","Joe","Saathvika"])
print("\n Last element of the array is:",names[-1])


 Last element of the array is: Saathvika


In [15]:
numbers = np.array([[5,8,7],[1,2,3],[4,7,9]])
print("Second Row,third element:",numbers[1][2])


Second Row,third element: 3


In [16]:
numbers = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
numbers[numbers%2==0]=10
print(numbers)

[10  1 10  3 10  5 10  7 10  9 10 11 10 13 10 15]


**Convert from 1D to 2D array**

In [18]:
numbers = np.arange(10)
print(numbers)
print("Reshaped into 2 dimensions:\n")
numbers.reshape(2, -1)

[0 1 2 3 4 5 6 7 8 9]
Reshaped into 2 dimensions:



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Import series using dictionary**

In [20]:
import pandas as pd
import numpy as np

sample_dict = {"x":1, "y":2, "z":3}
the_series = pd.Series(sample_dict)
print(the_series)

x    1
y    2
z    3
dtype: int64


**Assigning names to the series' index**

In [21]:
sample_series = pd.Series(list('123456789'))
sample_series.name = 'numbers'
sample_series.head()

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: object

**Converting NumPy array to Pandas dataframe**

In [22]:
sample_series = pd.Series(np.random.randint(1, 30, 25))
data_frame = pd.DataFrame(sample_series.values.reshape(5,5))
print(data_frame)

    0   1   2   3   4
0  11  15  14  20   2
1  20  17  19  19  17
2  26  24  18   6   6
3  15   1  27  14  20
4   7   9  25  29   6
